debug: true

server:
  port: 8002
  servlet:
    context-path: /spring-security

logging:
  level:
    com.obitosnn.*: debug
    '*': debug
    org.springframework.security: debug

spring:
  datasource:
    username: root
    password: 333
    url: jdbc:mysql://localhost:3306/spring-security-demo?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
  redis:
    host: 10.17.208.40
    port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath*:/mapper/**/*.xml
    - classpath*:/**/mapper/**/xml/*.xml
  global-config:
    db-config:
      id-type: ASSIGN_UUID
    banner: false
